/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import kelas.user;
import kelas.session;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author MyBook Hype AMD
 */
public class frameLogin extends javax.swing.JFrame {

    /**
     * Creates new form frameCategory
     */
    public frameLogin() {
        initComponents();
        // Ukuran JFrame
int frameWidth = 1280;
int frameHeight = 720;

// Ukuran elemen
int textFieldWidth = 400;
int textFieldHeight = 45;
int labelWidth = 400;
int labelHeight = 25;
int buttonWidth = 400;
int buttonHeight = 50;

// Hitung posisi X untuk center (horizontal)
int centerX = (frameWidth - textFieldWidth) / 2;

// Posisi Y untuk setiap elemen (vertical spacing)
int titleY = 100;
int startY = 200;
int spacing = 15;

// Label "Username :"
lblUsername.setBounds(centerX, startY, labelWidth, labelHeight);

// TextField Username
tUsername.setBounds(centerX, startY + labelHeight + 5, textFieldWidth, textFieldHeight);

// Label "Password :"
int passwordLabelY = startY + labelHeight + textFieldHeight + spacing + 5;
lblPassword.setBounds(centerX, passwordLabelY, labelWidth, labelHeight);

// PasswordField
int passwordFieldY = passwordLabelY + labelHeight + 5;
tPassword.setBounds(centerX, passwordFieldY, textFieldWidth, textFieldHeight);

// Checkbox "Show Password"
int checkboxY = passwordFieldY + textFieldHeight + 15;
cShow.setBounds(centerX, checkboxY, 200, 25);

// Button "Login"
int buttonY = checkboxY + 25 + 20;
bLogin.setBounds(centerX, buttonY, buttonWidth, buttonHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bLogin = new javax.swing.JButton();
        tUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cShow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 26, 46));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        bLogin.setBackground(new java.awt.Color(55, 80, 235));
        bLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        tUsername.setBackground(new java.awt.Color(237, 240, 245));
        tUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tUsername.setForeground(new java.awt.Color(51, 51, 51));
        tUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 252, 252), 1, true));
        tUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(102, 102, 255));
        lblUsername.setText("Username :");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(102, 102, 255));
        lblPassword.setText("Password :");

        tPassword.setBackground(new java.awt.Color(237, 240, 245));
        tPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tPassword.setForeground(new java.awt.Color(51, 51, 51));
        tPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(252, 252, 252), 1, true));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Login");

        cShow.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cShow.setForeground(new java.awt.Color(51, 0, 153));
        cShow.setText("Show Password");
        cShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cShow, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(477, 477, 477))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(598, 598, 598))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(74, 74, 74)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
       user usr = new user();
       
       usr.setUserName(tUsername.getText());
       usr.setUserPassword(tPassword.getText());
       usr.login();
       
       if(session.getStatus()=="aktif"){
           dispose();
           new dashboard().setVisible(true);
           
       }else{
           return;
       }
       
    }//GEN-LAST:event_bLoginActionPerformed

    private void cShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cShowActionPerformed
        // TODO add your handling code here:
        if (cShow.isSelected()) {
            // Tampilkan password
            tPassword.setEchoChar((char) 0);
        } else {
            // Sembunyikan password (default)
            tPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_cShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf fl = new FlatLightLaf();
        try {
            javax.swing.UIManager.setLookAndFeel(fl);
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox cShow;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
