/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import kelas.session;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPopupMenu;
import kelas.user;
/**
 *
 * @author MyBook Hype AMD
 */
public class frameDashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public frameDashboard() {
        initComponents();
        tUsername.setText(session.getUsername());
        tEmail.setText(session.getEmail());
        tFullName.setText(session.getFullname());
       
    }
// Di constructor atau initComponents

    // Attach ke label dengan icon
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuLogout = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tEmail = new javax.swing.JLabel();
        tFullName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tUsername = new javax.swing.JLabel();
        tUsername1 = new javax.swing.JLabel();
        tEmail1 = new javax.swing.JLabel();
        tFullName1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bKategori = new javax.swing.JButton();
        bUser = new javax.swing.JButton();
        bProduk = new javax.swing.JButton();
        hamburger = new javax.swing.JLabel();

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuLogout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 236, 239)));

        tEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tEmail.setText("Email :");

        tFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tFullName.setText("Nama : ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 37, 41));
        jLabel1.setText("Selamat Datang Di Aplikasi Super");

        tUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tUsername.setText("Username : ");

        tUsername1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tUsername1.setText("Username : ");

        tEmail1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tEmail1.setText("Email :");

        tFullName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tFullName1.setText("Nama : ");

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        bKategori.setBackground(new java.awt.Color(102, 153, 255));
        bKategori.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        bKategori.setForeground(new java.awt.Color(255, 255, 255));
        bKategori.setText("Kategori");
        bKategori.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bKategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKategoriActionPerformed(evt);
            }
        });

        bUser.setBackground(new java.awt.Color(102, 153, 255));
        bUser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        bUser.setForeground(new java.awt.Color(255, 255, 255));
        bUser.setText("User");
        bUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserActionPerformed(evt);
            }
        });

        bProduk.setBackground(new java.awt.Color(102, 153, 255));
        bProduk.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        bProduk.setForeground(new java.awt.Color(255, 255, 255));
        bProduk.setText("Produk");
        bProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProdukActionPerformed(evt);
            }
        });

        hamburger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hamburger-45.png"))); // NOI18N
        hamburger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburgerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(bKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(755, 755, 755)
                .addComponent(hamburger)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hamburger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tUsername1)
                                .addComponent(tEmail1))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tEmail)
                                .addComponent(tUsername)
                                .addComponent(tFullName))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tFullName1)
                        .addGap(37, 37, 37)))
                .addGap(479, 479, 479))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUsername)
                    .addComponent(tUsername1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEmail1)
                    .addComponent(tEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFullName)
                    .addComponent(tFullName1))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKategoriActionPerformed
        new frameCategory().setVisible(true);
    }//GEN-LAST:event_bKategoriActionPerformed

    private void hamburgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburgerMouseClicked
jPopupMenu1.show(hamburger, 0, hamburger.getHeight());     
    }//GEN-LAST:event_hamburgerMouseClicked

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(
    null,
    "Apakah kamu yakin ingin keluar?",
    "Konfirmasi Keluar",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE
);

if (pilihan == JOptionPane.YES_OPTION) {
    System.exit(0); 
} else if (pilihan == JOptionPane.NO_OPTION) {
    return;
}

    }//GEN-LAST:event_menuLogoutActionPerformed

    private void bProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProdukActionPerformed
        new frameProduct().setVisible(true);
    }//GEN-LAST:event_bProdukActionPerformed

    private void bUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserActionPerformed
      new FrameUser().setVisible(true);
    }//GEN-LAST:event_bUserActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf fl = new FlatLightLaf();
        javax.swing.UIManager.setLookAndFeel(fl);
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKategori;
    private javax.swing.JButton bProduk;
    private javax.swing.JButton bUser;
    private javax.swing.JLabel hamburger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JLabel tEmail;
    private javax.swing.JLabel tEmail1;
    private javax.swing.JLabel tFullName;
    private javax.swing.JLabel tFullName1;
    private javax.swing.JLabel tUsername;
    private javax.swing.JLabel tUsername1;
    // End of variables declaration//GEN-END:variables
}
